/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import domain.Clinica;
import domain.Paciente;
import domain.Registro;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcelo
 */
public class BuscarRegistro extends javax.swing.JFrame {

    Clinica cln = new Clinica();
    
    /**
     * Creates new form BuscarRegistro
     */
    public BuscarRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfPaciente = new javax.swing.JTextField();
        bAnterior = new javax.swing.JButton();
        bSiguiente = new javax.swing.JButton();
        tfDiagnostico = new javax.swing.JTextField();
        tfTratamiento = new javax.swing.JTextField();
        bVolver = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar Registro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 330, 50));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Tratamiento:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 150, 30));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("Paciente:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 110, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("Diganostico:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 150, 30));

        tfPaciente.setBackground(new java.awt.Color(0, 0, 51));
        tfPaciente.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tfPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 340, -1));

        bAnterior.setBackground(new java.awt.Color(0, 0, 51));
        bAnterior.setForeground(new java.awt.Color(102, 204, 255));
        bAnterior.setText("<<");
        bAnterior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        bAnterior.setFocusPainted(false);
        bAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnteriorActionPerformed(evt);
            }
        });
        jPanel1.add(bAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 40, 30));

        bSiguiente.setBackground(new java.awt.Color(0, 0, 51));
        bSiguiente.setForeground(new java.awt.Color(102, 204, 255));
        bSiguiente.setText(">>");
        bSiguiente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        bSiguiente.setFocusPainted(false);
        bSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(bSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 40, 30));

        tfDiagnostico.setBackground(new java.awt.Color(0, 0, 51));
        tfDiagnostico.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tfDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 340, -1));

        tfTratamiento.setBackground(new java.awt.Color(0, 0, 51));
        tfTratamiento.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tfTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 360, 30));

        bVolver.setBackground(new java.awt.Color(0, 0, 51));
        bVolver.setForeground(new java.awt.Color(102, 204, 255));
        bVolver.setText("Volver");
        bVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        bVolver.setFocusPainted(false);
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });
        jPanel1.add(bVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 70, 30));

        bModificar.setBackground(new java.awt.Color(0, 0, 51));
        bModificar.setForeground(new java.awt.Color(102, 204, 255));
        bModificar.setText("Modificar");
        bModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        bModificar.setFocusPainted(false);
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });
        jPanel1.add(bModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 290, 70, 30));

        bEliminar.setBackground(new java.awt.Color(0, 0, 51));
        bEliminar.setForeground(new java.awt.Color(102, 204, 255));
        bEliminar.setText("Eliminar");
        bEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        bEliminar.setFocusPainted(false);
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(bEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 290, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnteriorActionPerformed
        Registro e;
        boolean ant = this.cln.antRegistro();
        if(ant){
            e = this.cln.leerRegistroAct();
            this.mostrarRegistro(e);
        }else{
            JOptionPane.showMessageDialog(this, "Ya no hay pacientes para mostrar","Nueva Cita",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bAnteriorActionPerformed

    private void bSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguienteActionPerformed
        Registro e;
        boolean sig = this.cln.sigRegistro();

        if(sig){
            e = this.cln.leerRegistroAct();
            this.mostrarRegistro(e);
        }else{
            JOptionPane.showMessageDialog(this, "Ya no hay pacientes para mostrar","Nueva Cita",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bSiguienteActionPerformed

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_bVolverActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        Registro n = new Registro();
        n.setPac(this.tfPaciente.getText());
        n.setDiagnostico(this.tfDiagnostico.getText());
        n.setTratamiento(this.tfTratamiento.getText());
        this.cln.modificarRegistro(n);
    }//GEN-LAST:event_bModificarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cln.cargarRegistro();
        Registro n = this.cln.leerRegistroAct();
        this.mostrarRegistro(n);
    }//GEN-LAST:event_formWindowOpened

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        this.cln.eliminarRegistro();
        Registro p = this.cln.leerRegistro();
        this.mostrarRegistro(p);
        
    }//GEN-LAST:event_bEliminarActionPerformed

    private void mostrarRegistro(Registro p) {
        if (p != null) {
            this.tfPaciente.setText(p.getPac());
            this.tfDiagnostico.setText(p.getDiagnostico());
            this.tfTratamiento.setText(p.getTratamiento());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnterior;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bSiguiente;
    private javax.swing.JButton bVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfDiagnostico;
    private javax.swing.JTextField tfPaciente;
    private javax.swing.JTextField tfTratamiento;
    // End of variables declaration//GEN-END:variables
}
